### ISSUE TITLE
report.js のハードコードを解消する

### ISSUE THREAD

**Issue by inutano** [togodx/togodx-app#180]
@penqe @MarleenEliza  デプロイ先の変更を容易にするため `api.json` からのみ togodx 関連の api を参照するようにし、ハードコードをなくしたいです。現状以下の部分でハードコードされているようです。
https://github.com/togodx/togodx-app/blob/5d7b38f4ce63ee319f8ac8a37b8f300882d779b9/build/js/report.js#L2884
https://github.com/togodx/togodx-app/blob/5d7b38f4ce63ee319f8ac8a37b8f300882d779b9/build/js/report.js#L2885

**Comment by penqe** [comment]
@inutano report.js はスタンザ表示用のページで使っています。このページは使用しなくなるので、JS自体削除、という対応で良いでしょうか？
このイシューで聞くべきではないかもですが、 `5d7b38f move and rename` のコミットで、`frontend` 配下の `source` `build` が外出しされていますが、今後はこのディレクトリ構成で進めていく、で良いでしょうか。

**Comment by ktym** [comment]
frontoendディレクトリがなくなってたのは僕もどうしたのかな？と思っていました。どちらでもよいですけど。

**Comment by inutano** [comment]
おおなるほど、そうすると削除で構いません！よろしくお願いします。

**Comment by inutano** [comment]
外出しになってる件ですが、configとフロントのコードをレポジトリ分割したので、今後はこちらの構成でお願いできれば🙏

**Comment by inutano** [comment]
再度こちらのrepoをcloneしてから作業されるとよいかもです。

**Comment by penqe** [comment]
@inutano 諸々了解しました！　今日はちょっと時間作るのが難しそうで、明日以降の対応とさせてください。

**Comment by inutano** [comment]
前はconfigと分けるためにわざわざdir掘ってましたけど今はフロントのコードしかないのでわざわざfrontend dir切る意味ないので外に出しました

**Comment by ktym** [comment]
frontendフォルダは大田さんが作ってたのをレポジトリ分けたので不要になったってことか、了解です
