### ISSUE TITLE
View resultの画面で, 結果が0件 (No Data Found) だが, 矢印がくるくると回り続ける.

### ISSUE THREAD

**Issue by hchiba1** [togodx/togodx-app#229]
[リンク](https://togodx.dbcls.jp/human/?dataset=nando&annotations=%5B%7B%22attribute%22%3A%22compound_action_type_chembl%22%7D%5D&filters=%5B%7B%22attribute%22%3A%22compound_drug_indication_mesh_chembl%22%2C%22nodes%22%3A%5B%7B%22node%22%3A%22D007239%22%7D%5D%7D%2C%7B%22attribute%22%3A%22interaction_chembl_assay_existence_uniprot%22%2C%22nodes%22%3A%5B%7B%22node%22%3A%221%22%7D%5D%7D%5D)

**Comment by inutano** [comment]
fixed by #240
