### ISSUE TITLE
distributionのバーを選んでmap attributesしたとき, 結果が見えない

### ISSUE THREAD

**Issue by hchiba1** [togodx/togodx-app#232]
[リンク](https://togodx.dbcls.jp/human/?dataset=ensembl_gene&annotations=%5B%7B%22attribute%22%3A%22protein_domains_uniprot%22%7D%2C%7B%22attribute%22%3A%22protein_number_of_transmembrane_domains_uniprot%22%7D%5D&filters=%5B%7B%22attribute%22%3A%22gene_chromosome_ensembl%22%2C%22nodes%22%3A%5B%7B%22node%22%3A%2225%22%7D%5D%7D%5D)

**Comment by dsatoh** [comment]
Bugfixをtogodx-serverのdevelopブランチに適用しました。
https://github.com/togodx/togodx-server/tree/develop

**Comment by hchiba1** [comment]
ありがとうございます, 確認しました!
