### ISSUE TITLE
version: null が気持ち悪い

### ISSUE THREAD

**Issue by inutano** [togodx/togodx-app#233]
とのことです。バーを展開したときの左側、メタ情報が表示される部分。
JSON で `version: null` になっているときは version の部分をそもそも表示しない、とするのがよさそうです。

**Comment by inutano** [comment]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/221804/172115815-820cbcd6-c427-4806-96d8-419cb83e85a1.png">
こういうやつです

**Comment by penqe** [comment]
`N/A` にしているのですね。非表示化対応した方が良いでしょうか。 @inutano

**Comment by inutano** [comment]
お願いいたします〜〜 🙏

**Comment by penqe** [comment]
了解です。
こちらの対応が遅くて（すみません。。）、N/A にするように対応されたのかな、と思ったのでした。
`attributes[].source.version` に値がない場合は描画しないように変更しました。
最近フォーマッタを入れたため、手を加えた場所以外も若干コードが変わってます。

**Comment by inutano** [comment]
どうもありがとうございます！フォーマッタいいですね！
